// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqiw8_DvCiPsGvTJXMhvOw-7nVBAc_7vA',
    appId: '1:441510006418:web:626ca96373c292c2e2204b',
    messagingSenderId: '441510006418',
    projectId: 'kaala-teeka-2c7d3',
    authDomain: 'kaala-teeka-2c7d3.firebaseapp.com',
    storageBucket: 'kaala-teeka-2c7d3.firebasestorage.app',
    measurementId: 'G-3RKBRV09T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm_WpaBYMNjPbrl5HTMQ3hcMphT_JHUm4',
    appId: '1:441510006418:android:380f056f0ebca30ae2204b',
    messagingSenderId: '441510006418',
    projectId: 'kaala-teeka-2c7d3',
    storageBucket: 'kaala-teeka-2c7d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrOzXI8Gzi0mfntYeXIUzgaMAH_6XS9sA',
    appId: '1:441510006418:ios:370fc3ff65d8281be2204b',
    messagingSenderId: '441510006418',
    projectId: 'kaala-teeka-2c7d3',
    storageBucket: 'kaala-teeka-2c7d3.firebasestorage.app',
    iosBundleId: 'com.example.kaalaTeekaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrOzXI8Gzi0mfntYeXIUzgaMAH_6XS9sA',
    appId: '1:441510006418:ios:370fc3ff65d8281be2204b',
    messagingSenderId: '441510006418',
    projectId: 'kaala-teeka-2c7d3',
    storageBucket: 'kaala-teeka-2c7d3.firebasestorage.app',
    iosBundleId: 'com.example.kaalaTeekaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqiw8_DvCiPsGvTJXMhvOw-7nVBAc_7vA',
    appId: '1:441510006418:web:22da3f9b7f58233ae2204b',
    messagingSenderId: '441510006418',
    projectId: 'kaala-teeka-2c7d3',
    authDomain: 'kaala-teeka-2c7d3.firebaseapp.com',
    storageBucket: 'kaala-teeka-2c7d3.firebasestorage.app',
    measurementId: 'G-PCDWHTH90T',
  );

}